name: GitHub Readme Stats Fast Action
description: Generate GitHub Readme Stats cards using fast renderer.
author: Pranesh-2005

inputs:
  card:
    description: Card type (stats, top-langs, pin, streak, wakatime, gist)
    required: true

  options:
    description: Query options (query string or JSON)
    required: false
    default: ""

  path:
    description: Output SVG path
    required: false
    default: ""

  token:
    description: GitHub token (PAT or GITHUB_TOKEN)
    required: false
    default: ""

outputs:
  path:
    description: Path of generated SVG

runs:
  using: composite
  steps:
    # ✅ Install Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # ✅ Install pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    # ✅ Install deps via pnpm
    - name: Install dependencies
      run: pnpm install --prod --frozen-lockfile
      shell: bash
      working-directory: ${{ github.action_path }}

    # ✅ Run generator
    - name: Generate card
      run: node ${{ github.action_path }}/index.js
      shell: bash
      env:
        INPUT_CARD: ${{ inputs.card }}
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_PATH: ${{ inputs.path }}
        PAT_1: ${{ inputs.token }}

branding:
  icon: bar-chart-2
  color: blue
